language: go

go:
  - 1.x

env:
  - GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
#  - golint ./...
#  - golangci-lint run ./...
  - go test -race . -v
