language: go

go:
  - '1.12'

env:
  - GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  # - go test ./test -v
  - golint ./...
  - golangci-lint run ./...
